apiVersion: v1

kind: Service

metadata:
  name: lambda-asset-agent-options-service
  namespace: obolary
  labels:
    app: lambda-asset-agent-options

spec:
  selector:
    app: lambda-asset-agent-options
  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: apps/v1beta1

kind: Deployment

metadata:

  name: lambda-asset-agent-options-deployment
  namespace: obolary
  labels:
    app: lambda-asset-agent-options

spec:

  replicas: {{ REPLICAS }}

  template:

    metadata:
      labels:
        app: lambda-asset-agent-options

    spec:

      restartPolicy: Always
      terminationGracePeriodSeconds: 1

      containers:

      - name: lambda-asset-agent-options
        image: {{ TAG }}
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: 200m
            memory: 1Gi

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
